dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "6"

install:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

before_script:
  - ng -v

script:
  - ng lint
  - ng test --no-watch --code-coverage
  - npm run autoe2e

after_success:
  - npm run coveralls
  - npm run codacy

before_deploy:
  - ng build --prod

deploy:
    edge: true
    provider: cloudfoundry
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: development
    manifest: manifest.yml
